version: "3.9"

services:
  nextjs:
    build: ./verq-cms-client
    container_name: verq_nextjs
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./verq-cms-client/.env
    depends_on:
      - strapi

  strapi:
    build: ./verq-cms-server
    container_name: verq_strapi
    restart: unless-stopped
    ports:
      - "1337:1337"
    env_file:
      - ./verq-cms-server/.env
    volumes:
      - ./verq-cms-server/data:/app/.tmp