import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import LenisProvider from "@/wrapper/ScrollWrapper";
import { inter, orpix } from "@/fonts";
import Navbar from "@/components/Navigation/Navbar";
import RipplePlane from "@/components/Reusable/FluidCursor";
import Footer from "@/components/Navigation/Footer";

export const metadata: Metadata = {
  title: "Verq",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${orpix.variable} antialiased`}>
        {/* <LenisProvider> */}
        <RipplePlane />

        <Navbar />
        {children}
        <div className="bg-[#101010] relative z-50">
          <Footer />
        </div>

        {/* </LenisProvider> */}
        <Toaster
          position="top-right"
          toastOptions={{
            duration: 4000,
          }}
        />
      </body>
    </html>
  );
}
