services:
  postgres:
    image: postgres:16-alpine
    container_name: verq_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: verq-cms
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  strapi:
    build: .
    container_name: verq_strapi
    restart: unless-stopped
    ports:
      - "1337:1337"
    env_file:
      - .env
    volumes:
      - ./data:/app/.tmp
    depends_on:
      - postgres

volumes:
  postgres_data:
